### ISSUE TITLE
Bug: deleting a flight while it’s being uploaded breaks functionality 

### ISSUE THREAD

**Issue by zartom** [ericberman/MyFlightbookiOS#245]
As per title, and attached video, recent flight list does not update anymore and deleting the info message line crashes the app (trimmed the video due to privacy reasons as it crashes to the Home Screen)
In the video it was even after disabling WiFi but it still stays on the same uploading status

https://user-images.githubusercontent.com/1769078/129402073-c9ff40d8-00db-4ec4-b3ba-5756586b4864.mov

**Comment by ericberman** [comment]
Huh, shouldn't be able to delete any but an already-uploaded (or already pending) flight.  good bug.
