### ISSUE TITLE
Bug: Totals page doesn't total the property "Takeoffs - Non-towered airport"

### ISSUE THREAD

**Issue by zartom** [ericberman/MyFlightbookiOS#251]

**Comment by ericberman** [comment]
By design: you've indicated that you don't want this property by default.  Add it back in, and it will show up again.
![image](https://user-images.githubusercontent.com/16455286/133911872-90789af7-ced5-4121-ba28-999aecf53234.png)

**Comment by zartom** [comment]
I was under the impression that the totals page totals everything that was ever used - if I stopped flying into non towered airports, and don't want to see this property for new flights but still want to see that I've done hundreds of them in the best

**Comment by zartom** [comment]
Also unrelated but I cannot edit this list on mobile to check

**Comment by ericberman** [comment]
Nope, it's about removing clutter.  E.g., you record a bunch of stuff you need for a rating (like this very property), but once you have the rating it's just noise.  So the design of the feature is that it suppresses it from both previously used and from totals.  You can have a lot more flexibility about what's available for new flights vs. what's in totals if you use templates to control new flights.

You can edit this from iOS or Android by going to the profile page and finding the button there that takes you to additional settings on the site.  So on iOS go to Profile->Settings->Go to MyFlightbook.com
