### ISSUE TITLE
Adding flight times deletes remarks 

### ISSUE THREAD

**Issue by zartom** [ericberman/MyFlightbookiOS#267]
https://user-images.githubusercontent.com/1769078/145483732-eec380e5-d1b7-45ce-a601-db3eb095ed86.MP4

**Comment by ericberman** [comment]
wow, not sure how that happened.  My mac is in the shop today, can't even debug it...

**Comment by ericberman** [comment]
Looks like it’s not actually deleting, it’s restoring the previous value. Ie it’s not copying the value you typed into the backing flight data structure before refreshing everything from that structure. Probably a regression from issue #260. When we changed control types, probably lost the on-lost-focus event.

**Comment by ericberman** [comment]
Tapping/editing any other field does read the value and thus the edit box and the underlying data are in sync and tapping a time field has no I’ll effect

**Comment by ericberman** [comment]
One line fix.  Man, I hate apple: a single line control and a multi-line control are completely different controls and don't share the same notifications.  New build is submitted for review.

Good catch - thanks!

**Comment by zartom** [comment]
I don't know if it's related or if it's a regression, but now the "next-previous-delete" options in the on-screen keyboard tray bar do not work properly options when the focus is on the remarks window.

**Comment by ericberman** [comment]
I can't reproduce that.  It works fine for me, at least on my iPhone.
